version: 2.1

jobs:
 
 java-build:
    
    docker:
      - image: cimg/openjdk:11.0
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD            
    
    steps:
     
      - checkout
      
      - restore_cache:
          keys: 
          - cache-key-{{ checksum "pom.xml" }}
          - cache-key-
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: cache-key-{{ checksum "pom.xml" }}

      - run:
          name: Build
          command: mvn install

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/users-0.0.1-SNAPSHOT.jar

      - setup_remote_docker

      
      - run: 
          name: Publish Docker Image to Docker Hub
          command: |
                  echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
                  docker build -t asthadocker/docker_repo:circleci .
                  docker push asthadocker/docker_repo:circleci
      
            
 
 angular-build:

   #working_directory: ~/project/src/main/ui
   docker:
      - image: circleci/node:10.16.3

   steps:
    - checkout       
              
    - run:
          name: install-npm-wee
          command: cd src/main/ui && npm install   
    - run:
          name: run-app
          command : cd src/main/ui && npm start        
 
workflows:
  my_workflow_java: 
    jobs:
      - java-build
 # my_workflow_angular:    
  #  jobs:
   #   - angular-build
        
