version: 2.1

jobs:
 
 java-build:
    
    docker:
      - image: cimg/openjdk:11.0
    
    steps:
      
      - restore_cache:
          key: angular-java-example-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run:
          name: Build
          command: mvn install
      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/java-spring-0.0.1-SNAPSHOT.jar
          
      - run:
           name: Run
           command: java - jar target/java-spring-0.0.1-SNAPSHOT.jar


#angular-build:	

workflows:
  my_workflow_java_angular: 
    jobs:
      - java-build
