version: 2.1

jobs:
 
 java-build:
    
    docker:
      - image: cimg/openjdk:11.0
    
    steps:
     
      - checkout
      
      - restore_cache:
          keys: 
          - cache-key-{{ checksum "pom.xml" }}
          - cache-key-
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: cache-key-{{ checksum "pom.xml" }}

      - run:
          name: Build
          command: mvn install
      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/users-0.0.1-SNAPSHOT.jar
 angular-build:

   working_directory: /src/main/ui

   docker:
      - image: circleci/node:10.16.3

   steps:
    - checkout
              
    - run:
          name: install-npm-wee
          command: npm install
    - save_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules   
    - run:
          name: run-app
          command : npm start        


workflows:
  my_workflow_java: 
    jobs:
      - java-build
  my_workflow_angular:    
    jobs:
      - angular-build
        
